[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-set = "0.5.3"
itertools = "0.10.5"
nom = "7.1.3"
num = "0.4.0"
priority-queue = "1.3.1"
